name: Push Image

on:
  workflow_run:
    workflows: ['Build and Test']
    types:
      - completed

jobs:
  push-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      buildx_platforms: linux/amd64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        env:
          cache-name: docker-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./docker/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push unstable
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: ${{ env.buildx_platforms }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/latex:unstable
      - name: Determine release tag name
        if: ${{ github.event_name == 'release' }}
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build and push release
        if: ${{ github.event_name == 'release' }}
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: ${{ env.buildx_platforms }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/latex:${{steps.vars.outputs.tag}},
            ${{ secrets.DOCKERHUB_USERNAME }}/latex:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Checkout Git repository
        uses: actions/checkout@v2
      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          readme-filepath: README.md
          repository: gokhlayeh/latex
