name: push-image

on:
    push:
        branches: master
    release:
        types: [published, created, edited, prereleased]

jobs:
    main:
        runs-on: ubuntu-latest
        env:
            buildx_platforms: linux/amd64,linux/arm64
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up QEMU
              id: qemu
              uses: docker/setup-qemu-action@v1
              with:
                  platforms: all
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push latest
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  context: ./docker
                  file: ./docker/Dockerfile
                  platforms: ${{ env.buildx_platforms }}
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/latex:latest
            - name: Determine release tag name
              if: ${{ github.event_name == 'release' }}
              id: vars
              run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
            - name: Build and push release
              if: ${{ github.event_name == 'release' }}
              uses: docker/build-push-action@v2
              with:
                  context: ./docker
                  file: ./docker/Dockerfile
                  platforms: ${{ env.buildx_platforms }}
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/latex:${{steps.vars.outputs.tag}}
            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
            - name: Checkout Git repository
              uses: actions/checkout@v2
            - name: Update Docker Hub description
              uses: peter-evans/dockerhub-description@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
                  readme-filepath: README.md
                  repository: gokhlayeh/latex
