name: self-check

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
      - name: Run pre-commit checks
        uses: pre-commit/action@v2.0.0
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        env:
          cache-name: docker-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./docker/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build testing image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: ./docker
          file: ./docker/Dockerfile
          load: true
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/latex:testing
      - name: Compile EPS test document
        run: docker run -v "$(pwd):/github/workspace" -w /github/workspace/test/eps ${{ secrets.DOCKERHUB_USERNAME }}/latex:testing latexmk -outdir=build -pdf main.tex
      - name: Compile PlantUML test document
        run: docker run -v "$(pwd):/github/workspace" -w /github/workspace/test/plantuml ${{ secrets.DOCKERHUB_USERNAME }}/latex:testing latexmk -outdir=. -lualatex main.tex
      - name: Compile PythonTeX test document
        run: docker run -v "$(pwd):/github/workspace" -w /github/workspace/test/pythontex ${{ secrets.DOCKERHUB_USERNAME }}/latex:testing latexmk -outdir=build -pdf main.tex
      - name: Compile SVG test document
        run: docker run -v "$(pwd):/github/workspace" -w /github/workspace/test/svg ${{ secrets.DOCKERHUB_USERNAME }}/latex:testing latexmk -outdir=build -pdf main.tex
